language:
  objective-c
osx_image:
  xcode8
xcode_project:
  Logger.xcodeproj
xcode_scheme:
  Logger-iOS
script:
  - xcodebuild -project Logger.xcodeproj -scheme Logger-iOS 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.0' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -project Logger.xcodeproj -scheme Logger-MacOS clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
