language:
  objective-c
osx_image:
  xcode7.3
xcode_project:
  Logger.xcodeproj
xcode_scheme:
  Logger-iOS
script:
  - xctool -project Logger.xcodeproj -scheme Logger-iOS clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xctool -project Logger.xcodeproj -scheme Logger-MacOS clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
